### ISSUE TITLE
Unable to add SoftwareRequirement

### ISSUE THREAD

**Issue by matthdsm** [common-workflow-language/python-cwlgen#36]
Hi,

I'm trying to add SoftwareRequirement to a CommandLineTool instance like so

```
tool.hints.extend([
    cwlgen.SoftwareRequirement().SoftwarePackage(
       "bcl2fastq", version="2.20.0", specs=["https://identifiers.org/rrid/RRID:SCR_015058"]),
])
```
which seems to work, but produces invalid CWL where the `SoftwareRequirement` key is missing.

How do you recommend adding `SoftwarePackage`s to the CommandLineTool def?

Thanks
M

**Comment by matthdsm** [comment]
Or do you recommend going with cwl-utils instead of this project?

M

**Comment by illusional** [comment]
Hey @matthdsm, you can add it to the [`requirements.py`](https://github.com/common-workflow-language/python-cwlgen/blob/master/cwlgen/requirements.py) file. 

There’s one issue with CWL Utils  #27 before I see it as a viable replacement, but the intention is to deprecate this project as it supports different specs (where this is limited to CWL v1.0).

**Comment by matthdsm** [comment]
Hi @illusional 

Thanks for the quick reply!
The fact is, it's [already there](https://github.com/common-workflow-language/python-cwlgen/blob/master/cwlgen/requirements.py#L223) (great work on your part), but I'm unable to call it, since `SoftwareRequirement` takes no arguments.
How should I call `cwlgen.SoftwareRequirement`, so I can add a `SoftwarePackage` to it?

Thanks again
M

**Comment by illusional** [comment]
Ah @matthdsm,  you're absolutely right! I've added a quick fix to #37 for solve this. You can install it with `pip3 install git+https://github.com/common-workflow-language/python-cwlgen.git`, and then I'll release it if that's it. 

In the currently released version, you could do eg:

```python
sreq = cwlgen.SoftwareRequirement()
sreq.packages = [cwlgen.SoftwareRequirement.SoftwarePackage(**kwargs)]
```

In the new version (in Git master) you can do:
```python
sreq = cwlgen.SoftwareRequirement([cwlgen.SoftwareRequirement.SoftwarePackage(**kwargs)])
```

I can kick off a point release if this is all good.

**Comment by matthdsm** [comment]
Awesome! Thanks for the quick fix!

M

**Comment by illusional** [comment]
Actually fixed now.

**Comment by matthdsm** [comment]
Thanks for the fixes, but it seems we're not quite there yet.
using 
```
# hints
bcl2fastq_tool.hints.extend([
    cwlgen.SoftwareRequirement([cwlgen.SoftwareRequirement.SoftwarePackage(
        "bcl2fastq",
        version=["2.20.0"],
        specs=["https://identifiers.org/rrid/RRID:SCR_015058"]
    )])
])
```
yields the following yaml
```
hints:
- packages:
  - package: bcl2fastq
    specs:
    - https://identifiers.org/rrid/RRID:SCR_015058
    version:
    - 2.20.0
```

which is missing the `SoftwareRequirement` key and is invalid according to `cwltool`
The following formatting registers as correct
```
hints:
  SoftwareRequirement:
    packages:
      bcl2fastq:
        specs: ["https://identifiers.org/rrid/RRID:SCR_015058"]
        version: ["2.20.0"]
```

It seems to me the `SoftwareRequirement` key needs to be added and the `package` key from `SoftwarePackage` needs to be dropped.

Cheers
M

**Comment by illusional** [comment]
Hi @matthdsm, there was some special handling for `requirements` that didn't happen for hints. Could you give the current master another look, I've added #39 to address this separate issue?

**Comment by matthdsm** [comment]
Magnificent! Everything work great!

Thanks a lot, and thanks for the quick responses!

Cheers
M
