### ISSUE TITLE
New release for cwlgen

### ISSUE THREAD

**Issue by EiffL** [common-workflow-language/python-cwlgen#4]
I'm using this convenient library for putting some CWL functionality into a small pipeline engine project. In particular, I'm using the `Workflow` class in the master branch, which is unfortunately not yet part of a release. I really would like to be able to tell my users to simply `pip install cwlgen` but for the moment I need to have them install the current version on `master`.
Is there any plan for making a new release in the near future ? Or are there some issues that need to be addressed first (in which case I would be happy to help).

**Comment by hmenager** [comment]
@EiffL a new release has been created by @khillion: https://github.com/common-workflow-language/python-cwlgen/releases/tag/v0.2.1. Thanks a lot for your contributions, we apologize for the delay.

**Comment by EiffL** [comment]
Perfect, thanks so much !
