### ISSUE TITLE
documentation cwlgen.Workflow

### ISSUE THREAD

**Issue by matthdsm** [common-workflow-language/python-cwlgen#40]
Hi,

Would it be possible to add some doc's on how to create workflows and how to integrate previously created `CommandlineTools` into those workflows?

Thanks
M

**Comment by illusional** [comment]
Hi @matthdsm, the python-cwlgen project welcomes community contributions for documentation. You can fork the project and make changes in [`doc/source`](https://github.com/common-workflow-language/python-cwlgen/tree/master/doc/source) to any RST files.

Within the `doc` directory, you could `make html` to let `sphinx` create a static html page for you (readthedocs does this automatically on commit of this repo).

**Comment by mr-c** [comment]
Closing due to https://github.com/common-workflow-language/python-cwlgen#deprecated
