### ISSUE TITLE
unable to generate ExpressionTool

### ISSUE THREAD

**Issue by matthdsm** [common-workflow-language/python-cwlgen#43]
Hi,

I need to create an expressiontool to create a sample map based on a an array from a `glob` ouput. I seems like this is not implemented in the library, although the docs do refer to Expressiontools in WorkflowStep.

Am I missing something?

Thanks
M

**Comment by illusional** [comment]
Hey @matthdsm, python-cwlgen doesn't support creating an ExpressionTool, though happy to take a contribution. You're right the docs (and type annotations) do reference an ExpressionTool but none is current available.

**Comment by matthdsm** [comment]
I'll look into this if time allows. For now I think I'll just go with the pythonTool from janis.

Thanks anyway.
Cheers
M

**Comment by mr-c** [comment]
Closing due to https://github.com/common-workflow-language/python-cwlgen#deprecated
