### ISSUE TITLE
Not dumping empty lists doesn't conform to the spec

### ISSUE THREAD

**Issue by TMiguelT** [common-workflow-language/python-cwlgen#45]
Currently, `cwlgen.utils.should_exclude_object` will cause the exporter to skip empty lists. This means that if you have an empty list of outputs, the `output` key will *not* be included in the resulting CWL. However [the spec](https://www.commonwl.org/v1.1/CommandLineTool.html#CommandLineTool) requires that the outputs list be present. This causes an empty-output tool to fail validation under `cwltool`.

**Comment by illusional** [comment]
Thanks for the report @TMiguelT, this is fixed and released in `v0.4.1`.
