### ISSUE TITLE
creating input.yml

### ISSUE THREAD

**Issue by djarecka** [common-workflow-language/python-cwlgen#8]
Hi,

I've just trying to figure out what kind of files your package can generate. I understand that I can not create a cwl file with a `Workflow` class, but can I create an `input.yml` file for a cwl with a `CommandLineTool` class?

**Comment by khillion** [comment]
Hi,
The package supports the generation of CommandLineTool and also Workflow thanks to @kellrott.
Unfortunately, the creation of `input.yml` file is not possible yet but could be considered for future development.

**Comment by mr-c** [comment]
FYI: `cwltool` can create a blank input job document; this code may be of interest: https://github.com/common-workflow-language/cwltool/blob/840bb3b3ac889c9de33638ae8af707b5fd3fb326/cwltool/main.py#L61

**Comment by illusional** [comment]
Hey @djarecka, it appears your question was answered:
1. For existing CWL files, this project won't help you generate an inputs file - but [cwltool](https://github.com/common-workflow-language/cwltool) can. 
2. For workflows you build with these classes, you could add something like this to the Workflow class:

```python
def get_inputs_dict(self):
    return {i.id: None for i in workflow.inputs}
```

I'm going to close this issue in the meantime, but feel free to open it if you have more questions.
